% view_synthetic_ct.m
% ─────────────────────────────────────────────────────────────────────────────
% Synthetic CT Viewer — Slice Browser + 3D Skull Reconstruction
%
% Requires: matlab_export/synthetic_ct.mat (generated by export_to_mat.py)
%
% Controls:
%   Slice viewer : drag the slider to scroll through axial slices
%   3D viewer    : click "Rotate 3D" then drag; use threshold slider to adjust
% ─────────────────────────────────────────────────────────────────────────────

clear; clc; close all;

% ── Load data ─────────────────────────────────────────────────────────────────
data = load('matlab_export/synthetic_ct.mat');
ct   = double(data.synthetic_ct);   % (256, 256, N_slices)  range [0,1]

n_slices = size(ct, 3);
fprintf('Loaded volume: %d x %d x %d slices\n', size(ct,1), size(ct,2), n_slices);

% Flip slice direction so top-of-skull is at the top
ct_oriented = flip(ct, 3);

% ─────────────────────────────────────────────────────────────────────────────
% FIGURE 1 — Slice viewer with slider
% ─────────────────────────────────────────────────────────────────────────────
fig1 = figure('Name', 'Synthetic CT — Slice Viewer', ...
              'NumberTitle', 'off', ...
              'Position', [100 200 520 540]);

ax1 = axes('Parent', fig1, 'Position', [0.05 0.12 0.90 0.84]);
h_ct = imshow(ct_oriented(:,:,1), [], 'Parent', ax1);
colormap(ax1, gray);
title(ax1, 'Synthetic CT Output', 'FontSize', 13, 'FontWeight', 'bold');
axis(ax1, 'image', 'off');

% Slice label
slice_label = uicontrol(fig1, 'Style', 'text', ...
    'Units', 'normalized', ...
    'Position', [0.38 0.07 0.24 0.04], ...
    'String',   sprintf('Slice 1 / %d', n_slices), ...
    'FontSize', 10);

% Slider
slider = uicontrol(fig1, 'Style', 'slider', ...
    'Min', 1, 'Max', n_slices, 'Value', 1, ...
    'SliderStep', [1/(n_slices-1), 10/(n_slices-1)], ...
    'Units', 'normalized', ...
    'Position', [0.05 0.02 0.90 0.04], ...
    'Callback', @(src,~) sliderMoved(src, h_ct, slice_label, ct_oriented, n_slices, ax1));

% ─────────────────────────────────────────────────────────────────────────────
% FIGURE 2 — 3D Bone Reconstruction
% ─────────────────────────────────────────────────────────────────────────────
fig2 = figure('Name', '3D Cranial Reconstruction — Synthetic CT', ...
              'NumberTitle', 'off', ...
              'Position', [640 200 700 600], ...
              'Color', [0.12 0.12 0.12]);

bone_threshold = 0.47;

[p, ct_smooth] = buildSurface(ct_oriented, bone_threshold);

% Axes and lighting
daspect([1 1 1]);
axis tight off;
view(40, 22);
camlight('right');
camlight('left');
camlight('headlight');
lighting gouraud;
material([0.35 0.65 0.25 8 0.1]);

title('3D Cranial Reconstruction from Synthetic CT', ...
      'Color', 'white', 'FontSize', 13, 'FontWeight', 'bold');

% ── Controls ─────────────────────────────────────────────────────────────────
uicontrol(fig2, 'Style', 'togglebutton', ...
    'String', 'Rotate 3D', ...
    'Units', 'normalized', ...
    'Position', [0.01 0.01 0.12 0.05], ...
    'FontSize', 9, ...
    'Callback', @(s,~) toggleRotate(s));

uicontrol(fig2, 'Style', 'text', ...
    'String', 'Bone Threshold', ...
    'Units', 'normalized', ...
    'Position', [0.15 0.055 0.15 0.03], ...
    'FontSize', 8, ...
    'BackgroundColor', [0.12 0.12 0.12], ...
    'ForegroundColor', 'white');

thresh_slider = uicontrol(fig2, 'Style', 'slider', ...
    'Min', 0.30, 'Max', 0.70, 'Value', bone_threshold, ...
    'SliderStep', [0.01/0.40, 0.05/0.40], ...
    'Units', 'normalized', ...
    'Position', [0.15 0.01 0.40 0.04], ...
    'Callback', @(s,~) updateThreshold(s));

thresh_label = uicontrol(fig2, 'Style', 'text', ...
    'String', sprintf('%.2f', bone_threshold), ...
    'Units', 'normalized', ...
    'Position', [0.56 0.01 0.07 0.04], ...
    'FontSize', 9, ...
    'BackgroundColor', [0.12 0.12 0.12], ...
    'ForegroundColor', 'white');

% ── Nested callbacks ──────────────────────────────────────────────────────────
    function toggleRotate(src)
        if src.Value
            rotate3d(fig2, 'on');
        else
            rotate3d(fig2, 'off');
        end
    end

    function updateThreshold(src)
        new_thresh = src.Value;
        set(thresh_label, 'String', sprintf('%.2f', new_thresh));
        [new_p, new_smooth] = buildSurface(ct_oriented, new_thresh);
        if ~isempty(new_p)
            set(p, 'Faces',    new_p.Faces, ...
                   'Vertices', new_p.Vertices);
            isonormals(new_smooth, p);
            drawnow;
        end
    end

% ─────────────────────────────────────────────────────────────────────────────
% Helper — build isosurface patch from a CT volume + threshold
% ─────────────────────────────────────────────────────────────────────────────
function [p, ct_smooth] = buildSurface(ct_vol, threshold)
    p        = [];
    ct_smooth = [];

    bone_mask = ct_vol > threshold;
    CC        = bwconncomp(bone_mask, 6);

    if CC.NumObjects == 0
        warning('No bone voxels found at threshold %.2f', threshold);
        return;
    end

    cc_sizes    = cellfun(@numel, CC.PixelIdxList);
    [~, best]   = max(cc_sizes);
    clean_mask  = false(size(bone_mask));
    clean_mask(CC.PixelIdxList{best}) = true;

    ct_bone   = ct_vol .* double(clean_mask);
    ct_smooth = smooth3(ct_bone, 'gaussian', [3 3 3], 0.8);

    [faces, verts] = isosurface(ct_smooth, threshold * 0.95);

    if isempty(faces)
        warning('Isosurface empty at threshold %.2f', threshold);
        return;
    end

    p = patch('Faces', faces, 'Vertices', verts, ...
              'FaceColor', [0.88 0.82 0.74], ...
              'EdgeColor', 'none', ...
              'FaceAlpha', 0.92);
    isonormals(ct_smooth, p);

    fprintf('Surface: %d faces, %d vertices\n', size(faces,1), size(verts,1));
end

% ── Slice slider callback ─────────────────────────────────────────────────────
function sliderMoved(src, h_ct, slice_label, ct_oriented, n_slices, ax1)
    idx = round(src.Value);
    idx = max(1, min(idx, n_slices));   % clamp to valid range
    slc = ct_oriented(:,:,idx);
    set(h_ct, 'CData', slc);
    clim(ax1, [min(slc(:)) max(slc(:))]);
    set(slice_label,'String', sprintf('Slice %d / %d', idx, n_slices));
end